# Generated by Django 4.2.3 on 2023-07-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_foodimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodimage",
            name="image",
            field=models.ImageField(upload_to="%Y%m%d0.7248801876700609"),
        ),
    ]
