# Generated by Django 4.2.3 on 2023-07-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_alter_foodimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodimage",
            name="image",
            field=models.ImageField(upload_to="2023_07_18_17_03247441364558433999"),
        ),
    ]
