# Generated by Django 4.2.3 on 2023-07-18 11:11

from django.db import migrations, models
import food.utils


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_remove_foodimage_food_alter_foodimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=food.utils.rename_imagefile_to_uuid
            ),
        ),
    ]
