# Generated by Django 4.2.3 on 2023-07-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0009_alter_foodimage_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="foods",),
        migrations.RemoveField(model_name="foodimage", name="food",),
        migrations.DeleteModel(name="Food",),
        migrations.DeleteModel(name="User",),
    ]
