# Generated by Django 4.2.3 on 2023-07-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0010_remove_user_foods_remove_foodimage_food_delete_food_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="FoodImage", new_name="Image",),
    ]
