# Generated by Django 4.2.3 on 2023-07-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0012_image_foods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="foods",
            field=models.JSONField(default=dict, verbose_name="json"),
        ),
    ]
